### ISSUE TITLE
Seleção de itens da TableView nos favoritos

### ISSUE THREAD

**Issue by BeatrizLdS** [emillymaia/UselessFactsProject#1]
https://github.com/emillymaia/UselessFactsProject/blob/938191676467893acfda793a58e7fb694551e1c1/UselessFactsProject/Controller/FavoritesViewController.swift#L31-L40

Quando eu apenas seleciono um item na table view dos favoritados, eles ficam cima, mas apenas mudam de cor e nada acontece.
Vendo teu código (que está incrivelmente organizado), entendi a única ação na tua célula da table é o swipe para deletar, entendi certo?

Se não for ter nenhuma ação na seleção de células e se você quiser retirar esse efeito cinza da seleção, pode adicionar "cell.selectionStyle = .none" na criação/configuração da tua célula. Dessa forma:

```
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") else {
            return UITableViewCell(style: .default, reuseIdentifier: "Cell")
        }
        print(favoriteFacts[indexPath.row])
        var content = cell.defaultContentConfiguration()
        content.text = favoriteFacts[indexPath.row]
        cell.selectionStyle = .none
        cell.contentConfiguration = content
        return cell
}
```

Espero que possa te ajudar, caso seja de interesse seu. :D

**Comment by emillymaia** [comment]
Se eu te disser que na verdade eu nem havia clicado na minha célula, justamente por saber que ela não faz nada kkkk muito bom essa visão de fora pra ajudar a gente nos detalhes. Já ajustei e agradeço demais sua observação!!!
